[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gravityp"
version = "0.1.1"
authors = [
  { name="Alvaro Salazar-Cuadros", email="a.salazar@uva.es" },
  { name="Diego Saez-Chillon Gomez", email="diego.saez@uva.es" },

]
description = "GRAVITYp is a Python library to study the optical appearance of spherically symmetric compact objects in General Relativity. It stands for Geodesic RAys and Visualization of IntensiTY profiles."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26",
    "scipy>=1.11",
    "matplotlib>=3.8",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
notebooks = [
    "jupyter>=1.0",
    "ipykernel>=6.0",
]

[project.urls]
Homepage = "https://github.com/alvaroslzar/GRAVITYp"
Issues = "https://github.com/alvaroslzar/GRAVITYp/issues"